#!/bin/bash

set -e
#set -u
#set -x

cd $OMD_ROOT
mkdir -p var/top

export LD_LIBRARY_PATH="$OMD_ROOT/local/lib:$OMD_ROOT/lib"
export LC_ALL=C

# save top data
FILE="var/top/$(date +%s).log"
export COLUMNS=5000
set +e
gearman_top -b        > $FILE
top -c -b -n 2 -d 30 >> $FILE
gearman_top -b       >> $FILE
sed -i -e 's/\ *$//g'   $FILE
gzip -9 $FILE

# remove everything except last 7 days
ls -1tr var/top/*.log.gz var/top/*.log 2>/dev/null | head -n -10080 | xargs -r rm
